// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(spv_mobileFFI)
import spv_mobileFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_spv_mobile_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_spv_mobile_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureSpvMobileInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public struct AgreementParams {
    public var templateType: String
    public var payerAddress: String
    public var payeeAddress: String
    public var totalAmountSats: UInt64
    public var timeoutHeight: UInt64
    public var secretHashHex: String
    public var assetReference: String?
    public var paymentReference: String?
    public var documentHash: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(templateType: String, payerAddress: String, payeeAddress: String, totalAmountSats: UInt64, timeoutHeight: UInt64, secretHashHex: String, assetReference: String?, paymentReference: String?, documentHash: String?) {
        self.templateType = templateType
        self.payerAddress = payerAddress
        self.payeeAddress = payeeAddress
        self.totalAmountSats = totalAmountSats
        self.timeoutHeight = timeoutHeight
        self.secretHashHex = secretHashHex
        self.assetReference = assetReference
        self.paymentReference = paymentReference
        self.documentHash = documentHash
    }
}

#if compiler(>=6)
extension AgreementParams: Sendable {}
#endif


extension AgreementParams: Equatable, Hashable {
    public static func ==(lhs: AgreementParams, rhs: AgreementParams) -> Bool {
        if lhs.templateType != rhs.templateType {
            return false
        }
        if lhs.payerAddress != rhs.payerAddress {
            return false
        }
        if lhs.payeeAddress != rhs.payeeAddress {
            return false
        }
        if lhs.totalAmountSats != rhs.totalAmountSats {
            return false
        }
        if lhs.timeoutHeight != rhs.timeoutHeight {
            return false
        }
        if lhs.secretHashHex != rhs.secretHashHex {
            return false
        }
        if lhs.assetReference != rhs.assetReference {
            return false
        }
        if lhs.paymentReference != rhs.paymentReference {
            return false
        }
        if lhs.documentHash != rhs.documentHash {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(templateType)
        hasher.combine(payerAddress)
        hasher.combine(payeeAddress)
        hasher.combine(totalAmountSats)
        hasher.combine(timeoutHeight)
        hasher.combine(secretHashHex)
        hasher.combine(assetReference)
        hasher.combine(paymentReference)
        hasher.combine(documentHash)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAgreementParams: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AgreementParams {
        return
            try AgreementParams(
                templateType: FfiConverterString.read(from: &buf), 
                payerAddress: FfiConverterString.read(from: &buf), 
                payeeAddress: FfiConverterString.read(from: &buf), 
                totalAmountSats: FfiConverterUInt64.read(from: &buf), 
                timeoutHeight: FfiConverterUInt64.read(from: &buf), 
                secretHashHex: FfiConverterString.read(from: &buf), 
                assetReference: FfiConverterOptionString.read(from: &buf), 
                paymentReference: FfiConverterOptionString.read(from: &buf), 
                documentHash: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: AgreementParams, into buf: inout [UInt8]) {
        FfiConverterString.write(value.templateType, into: &buf)
        FfiConverterString.write(value.payerAddress, into: &buf)
        FfiConverterString.write(value.payeeAddress, into: &buf)
        FfiConverterUInt64.write(value.totalAmountSats, into: &buf)
        FfiConverterUInt64.write(value.timeoutHeight, into: &buf)
        FfiConverterString.write(value.secretHashHex, into: &buf)
        FfiConverterOptionString.write(value.assetReference, into: &buf)
        FfiConverterOptionString.write(value.paymentReference, into: &buf)
        FfiConverterOptionString.write(value.documentHash, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAgreementParams_lift(_ buf: RustBuffer) throws -> AgreementParams {
    return try FfiConverterTypeAgreementParams.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAgreementParams_lower(_ value: AgreementParams) -> RustBuffer {
    return FfiConverterTypeAgreementParams.lower(value)
}


public struct BalanceInfo {
    public var confirmed: UInt64
    public var utxoCount: UInt32
    public var height: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(confirmed: UInt64, utxoCount: UInt32, height: UInt64) {
        self.confirmed = confirmed
        self.utxoCount = utxoCount
        self.height = height
    }
}

#if compiler(>=6)
extension BalanceInfo: Sendable {}
#endif


extension BalanceInfo: Equatable, Hashable {
    public static func ==(lhs: BalanceInfo, rhs: BalanceInfo) -> Bool {
        if lhs.confirmed != rhs.confirmed {
            return false
        }
        if lhs.utxoCount != rhs.utxoCount {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(confirmed)
        hasher.combine(utxoCount)
        hasher.combine(height)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBalanceInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BalanceInfo {
        return
            try BalanceInfo(
                confirmed: FfiConverterUInt64.read(from: &buf), 
                utxoCount: FfiConverterUInt32.read(from: &buf), 
                height: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: BalanceInfo, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.confirmed, into: &buf)
        FfiConverterUInt32.write(value.utxoCount, into: &buf)
        FfiConverterUInt64.write(value.height, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBalanceInfo_lift(_ buf: RustBuffer) throws -> BalanceInfo {
    return try FfiConverterTypeBalanceInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBalanceInfo_lower(_ value: BalanceInfo) -> RustBuffer {
    return FfiConverterTypeBalanceInfo.lower(value)
}


public struct HtlcInfo {
    public var secretHashHex: String
    public var recipientAddress: String
    public var refundAddress: String
    public var timeoutHeight: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(secretHashHex: String, recipientAddress: String, refundAddress: String, timeoutHeight: UInt64) {
        self.secretHashHex = secretHashHex
        self.recipientAddress = recipientAddress
        self.refundAddress = refundAddress
        self.timeoutHeight = timeoutHeight
    }
}

#if compiler(>=6)
extension HtlcInfo: Sendable {}
#endif


extension HtlcInfo: Equatable, Hashable {
    public static func ==(lhs: HtlcInfo, rhs: HtlcInfo) -> Bool {
        if lhs.secretHashHex != rhs.secretHashHex {
            return false
        }
        if lhs.recipientAddress != rhs.recipientAddress {
            return false
        }
        if lhs.refundAddress != rhs.refundAddress {
            return false
        }
        if lhs.timeoutHeight != rhs.timeoutHeight {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(secretHashHex)
        hasher.combine(recipientAddress)
        hasher.combine(refundAddress)
        hasher.combine(timeoutHeight)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHtlcInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HtlcInfo {
        return
            try HtlcInfo(
                secretHashHex: FfiConverterString.read(from: &buf), 
                recipientAddress: FfiConverterString.read(from: &buf), 
                refundAddress: FfiConverterString.read(from: &buf), 
                timeoutHeight: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: HtlcInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.secretHashHex, into: &buf)
        FfiConverterString.write(value.recipientAddress, into: &buf)
        FfiConverterString.write(value.refundAddress, into: &buf)
        FfiConverterUInt64.write(value.timeoutHeight, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHtlcInfo_lift(_ buf: RustBuffer) throws -> HtlcInfo {
    return try FfiConverterTypeHtlcInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHtlcInfo_lower(_ value: HtlcInfo) -> RustBuffer {
    return FfiConverterTypeHtlcInfo.lower(value)
}


public struct LightClientConfig {
    public var seedlistPath: String
    public var extraPeer: String?
    public var startHeight: UInt64
    public var startHash: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(seedlistPath: String, extraPeer: String?, startHeight: UInt64, startHash: String?) {
        self.seedlistPath = seedlistPath
        self.extraPeer = extraPeer
        self.startHeight = startHeight
        self.startHash = startHash
    }
}

#if compiler(>=6)
extension LightClientConfig: Sendable {}
#endif


extension LightClientConfig: Equatable, Hashable {
    public static func ==(lhs: LightClientConfig, rhs: LightClientConfig) -> Bool {
        if lhs.seedlistPath != rhs.seedlistPath {
            return false
        }
        if lhs.extraPeer != rhs.extraPeer {
            return false
        }
        if lhs.startHeight != rhs.startHeight {
            return false
        }
        if lhs.startHash != rhs.startHash {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(seedlistPath)
        hasher.combine(extraPeer)
        hasher.combine(startHeight)
        hasher.combine(startHash)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLightClientConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LightClientConfig {
        return
            try LightClientConfig(
                seedlistPath: FfiConverterString.read(from: &buf), 
                extraPeer: FfiConverterOptionString.read(from: &buf), 
                startHeight: FfiConverterUInt64.read(from: &buf), 
                startHash: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: LightClientConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.seedlistPath, into: &buf)
        FfiConverterOptionString.write(value.extraPeer, into: &buf)
        FfiConverterUInt64.write(value.startHeight, into: &buf)
        FfiConverterOptionString.write(value.startHash, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightClientConfig_lift(_ buf: RustBuffer) throws -> LightClientConfig {
    return try FfiConverterTypeLightClientConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightClientConfig_lower(_ value: LightClientConfig) -> RustBuffer {
    return FfiConverterTypeLightClientConfig.lower(value)
}


public struct NodeStatus {
    public var height: UInt64
    public var peerCount: UInt32
    public var tipHash: String
    public var anchorLoaded: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(height: UInt64, peerCount: UInt32, tipHash: String, anchorLoaded: Bool) {
        self.height = height
        self.peerCount = peerCount
        self.tipHash = tipHash
        self.anchorLoaded = anchorLoaded
    }
}

#if compiler(>=6)
extension NodeStatus: Sendable {}
#endif


extension NodeStatus: Equatable, Hashable {
    public static func ==(lhs: NodeStatus, rhs: NodeStatus) -> Bool {
        if lhs.height != rhs.height {
            return false
        }
        if lhs.peerCount != rhs.peerCount {
            return false
        }
        if lhs.tipHash != rhs.tipHash {
            return false
        }
        if lhs.anchorLoaded != rhs.anchorLoaded {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(height)
        hasher.combine(peerCount)
        hasher.combine(tipHash)
        hasher.combine(anchorLoaded)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNodeStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NodeStatus {
        return
            try NodeStatus(
                height: FfiConverterUInt64.read(from: &buf), 
                peerCount: FfiConverterUInt32.read(from: &buf), 
                tipHash: FfiConverterString.read(from: &buf), 
                anchorLoaded: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: NodeStatus, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.height, into: &buf)
        FfiConverterUInt32.write(value.peerCount, into: &buf)
        FfiConverterString.write(value.tipHash, into: &buf)
        FfiConverterBool.write(value.anchorLoaded, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNodeStatus_lift(_ buf: RustBuffer) throws -> NodeStatus {
    return try FfiConverterTypeNodeStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNodeStatus_lower(_ value: NodeStatus) -> RustBuffer {
    return FfiConverterTypeNodeStatus.lower(value)
}


public struct TxRecord {
    public var txid: String
    public var height: UInt64
    public var netSats: Int64
    public var direction: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(txid: String, height: UInt64, netSats: Int64, direction: String) {
        self.txid = txid
        self.height = height
        self.netSats = netSats
        self.direction = direction
    }
}

#if compiler(>=6)
extension TxRecord: Sendable {}
#endif


extension TxRecord: Equatable, Hashable {
    public static func ==(lhs: TxRecord, rhs: TxRecord) -> Bool {
        if lhs.txid != rhs.txid {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        if lhs.netSats != rhs.netSats {
            return false
        }
        if lhs.direction != rhs.direction {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(txid)
        hasher.combine(height)
        hasher.combine(netSats)
        hasher.combine(direction)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTxRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TxRecord {
        return
            try TxRecord(
                txid: FfiConverterString.read(from: &buf), 
                height: FfiConverterUInt64.read(from: &buf), 
                netSats: FfiConverterInt64.read(from: &buf), 
                direction: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: TxRecord, into buf: inout [UInt8]) {
        FfiConverterString.write(value.txid, into: &buf)
        FfiConverterUInt64.write(value.height, into: &buf)
        FfiConverterInt64.write(value.netSats, into: &buf)
        FfiConverterString.write(value.direction, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTxRecord_lift(_ buf: RustBuffer) throws -> TxRecord {
    return try FfiConverterTypeTxRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTxRecord_lower(_ value: TxRecord) -> RustBuffer {
    return FfiConverterTypeTxRecord.lower(value)
}


public struct Utxo {
    public var txid: String
    public var index: UInt32
    public var value: UInt64
    public var height: UInt64
    public var isCoinbase: Bool
    public var scriptPubkeyHex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(txid: String, index: UInt32, value: UInt64, height: UInt64, isCoinbase: Bool, scriptPubkeyHex: String) {
        self.txid = txid
        self.index = index
        self.value = value
        self.height = height
        self.isCoinbase = isCoinbase
        self.scriptPubkeyHex = scriptPubkeyHex
    }
}

#if compiler(>=6)
extension Utxo: Sendable {}
#endif


extension Utxo: Equatable, Hashable {
    public static func ==(lhs: Utxo, rhs: Utxo) -> Bool {
        if lhs.txid != rhs.txid {
            return false
        }
        if lhs.index != rhs.index {
            return false
        }
        if lhs.value != rhs.value {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        if lhs.isCoinbase != rhs.isCoinbase {
            return false
        }
        if lhs.scriptPubkeyHex != rhs.scriptPubkeyHex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(txid)
        hasher.combine(index)
        hasher.combine(value)
        hasher.combine(height)
        hasher.combine(isCoinbase)
        hasher.combine(scriptPubkeyHex)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUtxo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Utxo {
        return
            try Utxo(
                txid: FfiConverterString.read(from: &buf), 
                index: FfiConverterUInt32.read(from: &buf), 
                value: FfiConverterUInt64.read(from: &buf), 
                height: FfiConverterUInt64.read(from: &buf), 
                isCoinbase: FfiConverterBool.read(from: &buf), 
                scriptPubkeyHex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Utxo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.txid, into: &buf)
        FfiConverterUInt32.write(value.index, into: &buf)
        FfiConverterUInt64.write(value.value, into: &buf)
        FfiConverterUInt64.write(value.height, into: &buf)
        FfiConverterBool.write(value.isCoinbase, into: &buf)
        FfiConverterString.write(value.scriptPubkeyHex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUtxo_lift(_ buf: RustBuffer) throws -> Utxo {
    return try FfiConverterTypeUtxo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUtxo_lower(_ value: Utxo) -> RustBuffer {
    return FfiConverterTypeUtxo.lower(value)
}


public struct WifKey {
    public var address: String
    public var pubkeyHex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(address: String, pubkeyHex: String) {
        self.address = address
        self.pubkeyHex = pubkeyHex
    }
}

#if compiler(>=6)
extension WifKey: Sendable {}
#endif


extension WifKey: Equatable, Hashable {
    public static func ==(lhs: WifKey, rhs: WifKey) -> Bool {
        if lhs.address != rhs.address {
            return false
        }
        if lhs.pubkeyHex != rhs.pubkeyHex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(address)
        hasher.combine(pubkeyHex)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWifKey: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WifKey {
        return
            try WifKey(
                address: FfiConverterString.read(from: &buf), 
                pubkeyHex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: WifKey, into buf: inout [UInt8]) {
        FfiConverterString.write(value.address, into: &buf)
        FfiConverterString.write(value.pubkeyHex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWifKey_lift(_ buf: RustBuffer) throws -> WifKey {
    return try FfiConverterTypeWifKey.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWifKey_lower(_ value: WifKey) -> RustBuffer {
    return FfiConverterTypeWifKey.lower(value)
}


public enum SpvError: Swift.Error {

    
    
    case InvalidArgument(message: String)
    
    case Network(message: String)
    
    case Rpc(message: String)
    
    case Wallet(message: String)
    
    case Parse(message: String)
    
    case Internal(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSpvError: FfiConverterRustBuffer {
    typealias SwiftType = SpvError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SpvError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidArgument(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Network(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .Rpc(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .Wallet(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .Parse(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .Internal(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SpvError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .InvalidArgument(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Network(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .Rpc(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .Wallet(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .Parse(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .Internal(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpvError_lift(_ buf: RustBuffer) throws -> SpvError {
    return try FfiConverterTypeSpvError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpvError_lower(_ value: SpvError) -> RustBuffer {
    return FfiConverterTypeSpvError.lower(value)
}


extension SpvError: Equatable, Hashable {}




extension SpvError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTxRecord: FfiConverterRustBuffer {
    typealias SwiftType = [TxRecord]

    public static func write(_ value: [TxRecord], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTxRecord.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TxRecord] {
        let len: Int32 = try readInt(&buf)
        var seq = [TxRecord]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTxRecord.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeUtxo: FfiConverterRustBuffer {
    typealias SwiftType = [Utxo]

    public static func write(_ value: [Utxo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeUtxo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Utxo] {
        let len: Int32 = try readInt(&buf)
        var seq = [Utxo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeUtxo.read(from: &buf))
        }
        return seq
    }
}
public func broadcastTx(txHex: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_broadcast_tx(
        FfiConverterString.lower(txHex),$0
    )
})
}
public func buildHtlcClaimTx(htlcTxid: String, htlcIndex: UInt32, htlcValue: UInt64, htlcScriptHex: String, preimageHex: String, seedHex: String, keyIndex: UInt32, toAddress: String, feeSats: UInt64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_build_htlc_claim_tx(
        FfiConverterString.lower(htlcTxid),
        FfiConverterUInt32.lower(htlcIndex),
        FfiConverterUInt64.lower(htlcValue),
        FfiConverterString.lower(htlcScriptHex),
        FfiConverterString.lower(preimageHex),
        FfiConverterString.lower(seedHex),
        FfiConverterUInt32.lower(keyIndex),
        FfiConverterString.lower(toAddress),
        FfiConverterUInt64.lower(feeSats),$0
    )
})
}
public func buildHtlcRefundTx(htlcTxid: String, htlcIndex: UInt32, htlcValue: UInt64, htlcScriptHex: String, seedHex: String, keyIndex: UInt32, toAddress: String, feeSats: UInt64, timeoutHeight: UInt64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_build_htlc_refund_tx(
        FfiConverterString.lower(htlcTxid),
        FfiConverterUInt32.lower(htlcIndex),
        FfiConverterUInt64.lower(htlcValue),
        FfiConverterString.lower(htlcScriptHex),
        FfiConverterString.lower(seedHex),
        FfiConverterUInt32.lower(keyIndex),
        FfiConverterString.lower(toAddress),
        FfiConverterUInt64.lower(feeSats),
        FfiConverterUInt64.lower(timeoutHeight),$0
    )
})
}
public func buildSendTx(utxos: [Utxo], toAddress: String, amountSats: UInt64, feeSats: UInt64, seedHex: String, fromIndex: UInt32)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_build_send_tx(
        FfiConverterSequenceTypeUtxo.lower(utxos),
        FfiConverterString.lower(toAddress),
        FfiConverterUInt64.lower(amountSats),
        FfiConverterUInt64.lower(feeSats),
        FfiConverterString.lower(seedHex),
        FfiConverterUInt32.lower(fromIndex),$0
    )
})
}
public func computeAgreementHash(agreementJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_compute_agreement_hash(
        FfiConverterString.lower(agreementJson),$0
    )
})
}
public func createAgreement(params: AgreementParams)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_create_agreement(
        FfiConverterTypeAgreementParams_lower(params),$0
    )
})
}
public func decodeHtlcv1(scriptHex: String)throws  -> HtlcInfo  {
    return try  FfiConverterTypeHtlcInfo_lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_decode_htlcv1(
        FfiConverterString.lower(scriptHex),$0
    )
})
}
public func deriveAddress(seedHex: String, index: UInt32)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_derive_address(
        FfiConverterString.lower(seedHex),
        FfiConverterUInt32.lower(index),$0
    )
})
}
public func derivePrivkeyHex(seedHex: String, index: UInt32)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_derive_privkey_hex(
        FfiConverterString.lower(seedHex),
        FfiConverterUInt32.lower(index),$0
    )
})
}
public func encodeHtlcv1(secretHashHex: String, recipientAddress: String, refundAddress: String, timeoutHeight: UInt64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_encode_htlcv1(
        FfiConverterString.lower(secretHashHex),
        FfiConverterString.lower(recipientAddress),
        FfiConverterString.lower(refundAddress),
        FfiConverterUInt64.lower(timeoutHeight),$0
    )
})
}
public func exportWif(seedHex: String, index: UInt32)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_export_wif(
        FfiConverterString.lower(seedHex),
        FfiConverterUInt32.lower(index),$0
    )
})
}
public func generateMnemonic()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_generate_mnemonic($0
    )
})
}
public func getSyncedHeight() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_spv_mobile_fn_func_get_synced_height($0
    )
})
}
public func getTipHash() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_spv_mobile_fn_func_get_tip_hash($0
    )
})
}
public func importWif(wif: String)throws  -> WifKey  {
    return try  FfiConverterTypeWifKey_lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_import_wif(
        FfiConverterString.lower(wif),$0
    )
})
}
public func isSyncing() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_spv_mobile_fn_func_is_syncing($0
    )
})
}
public func mnemonicToSeed(mnemonic: String, passphrase: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_mnemonic_to_seed(
        FfiConverterString.lower(mnemonic),
        FfiConverterString.lower(passphrase),$0
    )
})
}
public func peerCount() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_spv_mobile_fn_func_peer_count($0
    )
})
}
public func rpcGetBalance(rpcUrl: String, authToken: String?, address: String)throws  -> BalanceInfo  {
    return try  FfiConverterTypeBalanceInfo_lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_rpc_get_balance(
        FfiConverterString.lower(rpcUrl),
        FfiConverterOptionString.lower(authToken),
        FfiConverterString.lower(address),$0
    )
})
}
public func rpcGetFeeRate(rpcUrl: String, authToken: String?)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_rpc_get_fee_rate(
        FfiConverterString.lower(rpcUrl),
        FfiConverterOptionString.lower(authToken),$0
    )
})
}
public func rpcGetHistory(rpcUrl: String, authToken: String?, address: String)throws  -> [TxRecord]  {
    return try  FfiConverterSequenceTypeTxRecord.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_rpc_get_history(
        FfiConverterString.lower(rpcUrl),
        FfiConverterOptionString.lower(authToken),
        FfiConverterString.lower(address),$0
    )
})
}
public func rpcGetStatus(rpcUrl: String, authToken: String?)throws  -> NodeStatus  {
    return try  FfiConverterTypeNodeStatus_lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_rpc_get_status(
        FfiConverterString.lower(rpcUrl),
        FfiConverterOptionString.lower(authToken),$0
    )
})
}
public func rpcGetUtxos(rpcUrl: String, authToken: String?, address: String)throws  -> [Utxo]  {
    return try  FfiConverterSequenceTypeUtxo.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_rpc_get_utxos(
        FfiConverterString.lower(rpcUrl),
        FfiConverterOptionString.lower(authToken),
        FfiConverterString.lower(address),$0
    )
})
}
public func rpcSubmitTx(rpcUrl: String, authToken: String?, txHex: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_rpc_submit_tx(
        FfiConverterString.lower(rpcUrl),
        FfiConverterOptionString.lower(authToken),
        FfiConverterString.lower(txHex),$0
    )
})
}
public func startLightClient(config: LightClientConfig)throws   {try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_start_light_client(
        FfiConverterTypeLightClientConfig_lower(config),$0
    )
}
}
public func stopLightClient()  {try! rustCall() {
    uniffi_spv_mobile_fn_func_stop_light_client($0
    )
}
}
public func validateAddress(address: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_spv_mobile_fn_func_validate_address(
        FfiConverterString.lower(address),$0
    )
})
}
public func verifyMerkleProof(txidHex: String, merkleRootHex: String, proofHexNodes: [String], index: UInt64)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeSpvError_lift) {
    uniffi_spv_mobile_fn_func_verify_merkle_proof(
        FfiConverterString.lower(txidHex),
        FfiConverterString.lower(merkleRootHex),
        FfiConverterSequenceString.lower(proofHexNodes),
        FfiConverterUInt64.lower(index),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_spv_mobile_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_spv_mobile_checksum_func_broadcast_tx() != 64231) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_build_htlc_claim_tx() != 41904) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_build_htlc_refund_tx() != 37240) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_build_send_tx() != 5310) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_compute_agreement_hash() != 39470) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_create_agreement() != 61147) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_decode_htlcv1() != 36657) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_derive_address() != 48495) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_derive_privkey_hex() != 2218) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_encode_htlcv1() != 32890) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_export_wif() != 22899) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_generate_mnemonic() != 40812) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_get_synced_height() != 49504) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_get_tip_hash() != 9205) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_import_wif() != 41385) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_is_syncing() != 25319) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_mnemonic_to_seed() != 24489) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_peer_count() != 59695) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_rpc_get_balance() != 65347) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_rpc_get_fee_rate() != 13276) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_rpc_get_history() != 34387) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_rpc_get_status() != 23553) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_rpc_get_utxos() != 41075) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_rpc_submit_tx() != 4884) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_start_light_client() != 50771) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_stop_light_client() != 54926) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_validate_address() != 4701) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spv_mobile_checksum_func_verify_merkle_proof() != 32895) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureSpvMobileInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all