// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_BROADCAST_TX
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_BROADCAST_TX
RustBuffer uniffi_spv_mobile_fn_func_broadcast_tx(RustBuffer tx_hex, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_BUILD_HTLC_CLAIM_TX
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_BUILD_HTLC_CLAIM_TX
RustBuffer uniffi_spv_mobile_fn_func_build_htlc_claim_tx(RustBuffer htlc_txid, uint32_t htlc_index, uint64_t htlc_value, RustBuffer htlc_script_hex, RustBuffer preimage_hex, RustBuffer seed_hex, uint32_t key_index, RustBuffer to_address, uint64_t fee_sats, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_BUILD_HTLC_REFUND_TX
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_BUILD_HTLC_REFUND_TX
RustBuffer uniffi_spv_mobile_fn_func_build_htlc_refund_tx(RustBuffer htlc_txid, uint32_t htlc_index, uint64_t htlc_value, RustBuffer htlc_script_hex, RustBuffer seed_hex, uint32_t key_index, RustBuffer to_address, uint64_t fee_sats, uint64_t timeout_height, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_BUILD_SEND_TX
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_BUILD_SEND_TX
RustBuffer uniffi_spv_mobile_fn_func_build_send_tx(RustBuffer utxos, RustBuffer to_address, uint64_t amount_sats, uint64_t fee_sats, RustBuffer seed_hex, uint32_t from_index, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_COMPUTE_AGREEMENT_HASH
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_COMPUTE_AGREEMENT_HASH
RustBuffer uniffi_spv_mobile_fn_func_compute_agreement_hash(RustBuffer agreement_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_CREATE_AGREEMENT
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_CREATE_AGREEMENT
RustBuffer uniffi_spv_mobile_fn_func_create_agreement(RustBuffer params, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_DECODE_HTLCV1
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_DECODE_HTLCV1
RustBuffer uniffi_spv_mobile_fn_func_decode_htlcv1(RustBuffer script_hex, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_DERIVE_ADDRESS
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_DERIVE_ADDRESS
RustBuffer uniffi_spv_mobile_fn_func_derive_address(RustBuffer seed_hex, uint32_t index, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_DERIVE_PRIVKEY_HEX
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_DERIVE_PRIVKEY_HEX
RustBuffer uniffi_spv_mobile_fn_func_derive_privkey_hex(RustBuffer seed_hex, uint32_t index, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_ENCODE_HTLCV1
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_ENCODE_HTLCV1
RustBuffer uniffi_spv_mobile_fn_func_encode_htlcv1(RustBuffer secret_hash_hex, RustBuffer recipient_address, RustBuffer refund_address, uint64_t timeout_height, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_EXPORT_WIF
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_EXPORT_WIF
RustBuffer uniffi_spv_mobile_fn_func_export_wif(RustBuffer seed_hex, uint32_t index, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_GENERATE_MNEMONIC
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_GENERATE_MNEMONIC
RustBuffer uniffi_spv_mobile_fn_func_generate_mnemonic(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_GET_SYNCED_HEIGHT
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_GET_SYNCED_HEIGHT
uint64_t uniffi_spv_mobile_fn_func_get_synced_height(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_GET_TIP_HASH
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_GET_TIP_HASH
RustBuffer uniffi_spv_mobile_fn_func_get_tip_hash(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_IMPORT_WIF
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_IMPORT_WIF
RustBuffer uniffi_spv_mobile_fn_func_import_wif(RustBuffer wif, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_IS_SYNCING
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_IS_SYNCING
int8_t uniffi_spv_mobile_fn_func_is_syncing(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_MNEMONIC_TO_SEED
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_MNEMONIC_TO_SEED
RustBuffer uniffi_spv_mobile_fn_func_mnemonic_to_seed(RustBuffer mnemonic, RustBuffer passphrase, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_PEER_COUNT
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_PEER_COUNT
uint32_t uniffi_spv_mobile_fn_func_peer_count(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_RPC_GET_BALANCE
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_RPC_GET_BALANCE
RustBuffer uniffi_spv_mobile_fn_func_rpc_get_balance(RustBuffer rpc_url, RustBuffer auth_token, RustBuffer address, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_RPC_GET_FEE_RATE
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_RPC_GET_FEE_RATE
uint64_t uniffi_spv_mobile_fn_func_rpc_get_fee_rate(RustBuffer rpc_url, RustBuffer auth_token, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_RPC_GET_HISTORY
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_RPC_GET_HISTORY
RustBuffer uniffi_spv_mobile_fn_func_rpc_get_history(RustBuffer rpc_url, RustBuffer auth_token, RustBuffer address, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_RPC_GET_STATUS
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_RPC_GET_STATUS
RustBuffer uniffi_spv_mobile_fn_func_rpc_get_status(RustBuffer rpc_url, RustBuffer auth_token, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_RPC_GET_UTXOS
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_RPC_GET_UTXOS
RustBuffer uniffi_spv_mobile_fn_func_rpc_get_utxos(RustBuffer rpc_url, RustBuffer auth_token, RustBuffer address, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_RPC_SUBMIT_TX
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_RPC_SUBMIT_TX
RustBuffer uniffi_spv_mobile_fn_func_rpc_submit_tx(RustBuffer rpc_url, RustBuffer auth_token, RustBuffer tx_hex, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_START_LIGHT_CLIENT
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_START_LIGHT_CLIENT
void uniffi_spv_mobile_fn_func_start_light_client(RustBuffer config, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_STOP_LIGHT_CLIENT
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_STOP_LIGHT_CLIENT
void uniffi_spv_mobile_fn_func_stop_light_client(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_VALIDATE_ADDRESS
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_VALIDATE_ADDRESS
int8_t uniffi_spv_mobile_fn_func_validate_address(RustBuffer address, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_VERIFY_MERKLE_PROOF
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_FN_FUNC_VERIFY_MERKLE_PROOF
int8_t uniffi_spv_mobile_fn_func_verify_merkle_proof(RustBuffer txid_hex, RustBuffer merkle_root_hex, RustBuffer proof_hex_nodes, uint64_t index, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUSTBUFFER_ALLOC
RustBuffer ffi_spv_mobile_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_spv_mobile_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUSTBUFFER_FREE
void ffi_spv_mobile_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUSTBUFFER_RESERVE
RustBuffer ffi_spv_mobile_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_U8
void ffi_spv_mobile_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_U8
void ffi_spv_mobile_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_U8
void ffi_spv_mobile_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_spv_mobile_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_I8
void ffi_spv_mobile_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_I8
void ffi_spv_mobile_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_I8
void ffi_spv_mobile_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_I8
int8_t ffi_spv_mobile_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_U16
void ffi_spv_mobile_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_U16
void ffi_spv_mobile_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_U16
void ffi_spv_mobile_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_spv_mobile_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_I16
void ffi_spv_mobile_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_I16
void ffi_spv_mobile_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_I16
void ffi_spv_mobile_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_I16
int16_t ffi_spv_mobile_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_U32
void ffi_spv_mobile_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_U32
void ffi_spv_mobile_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_U32
void ffi_spv_mobile_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_spv_mobile_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_I32
void ffi_spv_mobile_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_I32
void ffi_spv_mobile_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_I32
void ffi_spv_mobile_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_I32
int32_t ffi_spv_mobile_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_U64
void ffi_spv_mobile_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_U64
void ffi_spv_mobile_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_U64
void ffi_spv_mobile_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_spv_mobile_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_I64
void ffi_spv_mobile_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_I64
void ffi_spv_mobile_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_I64
void ffi_spv_mobile_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_I64
int64_t ffi_spv_mobile_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_F32
void ffi_spv_mobile_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_F32
void ffi_spv_mobile_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_F32
void ffi_spv_mobile_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_F32
float ffi_spv_mobile_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_F64
void ffi_spv_mobile_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_F64
void ffi_spv_mobile_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_F64
void ffi_spv_mobile_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_F64
double ffi_spv_mobile_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_POINTER
void ffi_spv_mobile_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_POINTER
void ffi_spv_mobile_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_POINTER
void ffi_spv_mobile_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_spv_mobile_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_spv_mobile_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_spv_mobile_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_spv_mobile_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_spv_mobile_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_POLL_VOID
void ffi_spv_mobile_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_CANCEL_VOID
void ffi_spv_mobile_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_FREE_VOID
void ffi_spv_mobile_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_RUST_FUTURE_COMPLETE_VOID
void ffi_spv_mobile_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_BROADCAST_TX
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_BROADCAST_TX
uint16_t uniffi_spv_mobile_checksum_func_broadcast_tx(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_BUILD_HTLC_CLAIM_TX
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_BUILD_HTLC_CLAIM_TX
uint16_t uniffi_spv_mobile_checksum_func_build_htlc_claim_tx(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_BUILD_HTLC_REFUND_TX
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_BUILD_HTLC_REFUND_TX
uint16_t uniffi_spv_mobile_checksum_func_build_htlc_refund_tx(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_BUILD_SEND_TX
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_BUILD_SEND_TX
uint16_t uniffi_spv_mobile_checksum_func_build_send_tx(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_COMPUTE_AGREEMENT_HASH
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_COMPUTE_AGREEMENT_HASH
uint16_t uniffi_spv_mobile_checksum_func_compute_agreement_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_CREATE_AGREEMENT
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_CREATE_AGREEMENT
uint16_t uniffi_spv_mobile_checksum_func_create_agreement(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_DECODE_HTLCV1
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_DECODE_HTLCV1
uint16_t uniffi_spv_mobile_checksum_func_decode_htlcv1(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_DERIVE_ADDRESS
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_DERIVE_ADDRESS
uint16_t uniffi_spv_mobile_checksum_func_derive_address(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_DERIVE_PRIVKEY_HEX
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_DERIVE_PRIVKEY_HEX
uint16_t uniffi_spv_mobile_checksum_func_derive_privkey_hex(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_ENCODE_HTLCV1
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_ENCODE_HTLCV1
uint16_t uniffi_spv_mobile_checksum_func_encode_htlcv1(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_EXPORT_WIF
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_EXPORT_WIF
uint16_t uniffi_spv_mobile_checksum_func_export_wif(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_GENERATE_MNEMONIC
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_GENERATE_MNEMONIC
uint16_t uniffi_spv_mobile_checksum_func_generate_mnemonic(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_GET_SYNCED_HEIGHT
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_GET_SYNCED_HEIGHT
uint16_t uniffi_spv_mobile_checksum_func_get_synced_height(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_GET_TIP_HASH
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_GET_TIP_HASH
uint16_t uniffi_spv_mobile_checksum_func_get_tip_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_IMPORT_WIF
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_IMPORT_WIF
uint16_t uniffi_spv_mobile_checksum_func_import_wif(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_IS_SYNCING
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_IS_SYNCING
uint16_t uniffi_spv_mobile_checksum_func_is_syncing(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_MNEMONIC_TO_SEED
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_MNEMONIC_TO_SEED
uint16_t uniffi_spv_mobile_checksum_func_mnemonic_to_seed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_PEER_COUNT
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_PEER_COUNT
uint16_t uniffi_spv_mobile_checksum_func_peer_count(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_RPC_GET_BALANCE
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_RPC_GET_BALANCE
uint16_t uniffi_spv_mobile_checksum_func_rpc_get_balance(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_RPC_GET_FEE_RATE
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_RPC_GET_FEE_RATE
uint16_t uniffi_spv_mobile_checksum_func_rpc_get_fee_rate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_RPC_GET_HISTORY
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_RPC_GET_HISTORY
uint16_t uniffi_spv_mobile_checksum_func_rpc_get_history(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_RPC_GET_STATUS
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_RPC_GET_STATUS
uint16_t uniffi_spv_mobile_checksum_func_rpc_get_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_RPC_GET_UTXOS
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_RPC_GET_UTXOS
uint16_t uniffi_spv_mobile_checksum_func_rpc_get_utxos(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_RPC_SUBMIT_TX
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_RPC_SUBMIT_TX
uint16_t uniffi_spv_mobile_checksum_func_rpc_submit_tx(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_START_LIGHT_CLIENT
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_START_LIGHT_CLIENT
uint16_t uniffi_spv_mobile_checksum_func_start_light_client(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_STOP_LIGHT_CLIENT
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_STOP_LIGHT_CLIENT
uint16_t uniffi_spv_mobile_checksum_func_stop_light_client(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_VALIDATE_ADDRESS
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_VALIDATE_ADDRESS
uint16_t uniffi_spv_mobile_checksum_func_validate_address(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_VERIFY_MERKLE_PROOF
#define UNIFFI_FFIDEF_UNIFFI_SPV_MOBILE_CHECKSUM_FUNC_VERIFY_MERKLE_PROOF
uint16_t uniffi_spv_mobile_checksum_func_verify_merkle_proof(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SPV_MOBILE_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_SPV_MOBILE_UNIFFI_CONTRACT_VERSION
uint32_t ffi_spv_mobile_uniffi_contract_version(void
    
);
#endif

